default_language_version:
    python: python3
default_stages: [ commit ]

repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.3
    hooks:
    - id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    - id: isort
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: flake8
      # - id: detect-private-key
      # - id: check-yaml
      # args: [--allow-multiple-documents]
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-merge-conflict
    - id: check-toml
    - id: requirements-txt-fixer
-   repo: https://github.com/getasnap/snap-pre-commit-hooks
    rev: v1.10
    hooks:
    - id: prepend-branch-name
-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 1.11.2
    hooks:
    - id: markdownlint
-   repo: https://github.com/Lucas-C/pre-commit-hooks-markup
    rev: v1.0.0
    hooks:
    - id: rst-linter
